#!/bin/sh
#/etc/init.d/videodromm
export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
start)
#exec forever --sourceDir=/usr/local/bin/videodromm-server -p /usr/local/bin/videodromm-server index.js  #scriptarguments
./usr/local/bin/videodromm-server/npm start
;;
stop)
exec forever stop --sourceDir=/usr/local/bin/videodromm-server index.js
;;
*)
echo "Usage: /etc/init.d/videodromm {start|stop}"
exit 1
;;
esac
exit 0

